import Foundation

// MARK: - AutoRegistrable Protocol

/// Protocol for types that can be automatically registered with the DI container.
/// Conformance is generated by the `@AutoRegister` macro.
public protocol AutoRegistrable {
    /// Registers this type with the given container.
    /// - Parameter container: The container to register with.
    static func autoRegister(in container: Injectable)
}

// MARK: - Auto Registry

/// Extension on Container for bootstrapping auto-registered dependencies.
public extension Container {
    
    /// Bootstraps all auto-registered types into the container.
    ///
    /// Call this once at app startup:
    /// ```swift
    /// @main
    /// struct MyApp: App {
    ///     init() {
    ///         Container.standard.bootstrap(
    ///             MyService.self,
    ///             OtherService.self
    ///         )
    ///     }
    /// }
    /// ```
    ///
    /// - Parameter types: The types to register (must conform to `AutoRegistrable`).
    func bootstrap(_ types: AutoRegistrable.Type...) {
        for type in types {
            type.autoRegister(in: self)
        }
    }
    
    /// Variadic generic version using parameter packs.
    /// Registers all provided types in a single call with compile-time type safety.
    func bootstrap<each T: AutoRegistrable>(_ types: repeat (each T).Type) {
        repeat (each T).autoRegister(in: self)
    }
}
